{
 "title": "Node View",
 "description": "Node Exporter System Metrics",
 "tags": [ "Moneo Refined" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   },
   { "name": "Datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=\"$instance\"}, cpu)"
    }
   },
   {
    "name": "diskdevices",
    "label": "Disk Devices",
    "query": {
     "query": "label_values(node_disk_reads_completed_total{instance=\"$instance\"}, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "CPU Utilization",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - avg by (instance, cpu) (rate(node_cpu_seconds_total{mode='idle', instance=~\"$instance\", cpu=~\"$cpu\"}[5m]))))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Clock",
   "type": "timeseries",
   "description": "CPU Clock Speed",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=~\"$instance\", cpu=~\"$cpu\"} / 1000000",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  { "title": "Memory Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Memory Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - node_memory_memavailable_bytes{instance=~\"$instance\"} / node_memory_memtotal_bytes{instance=~\"$instance\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "description": "Available memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "node_memory_memavailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Network Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Ethernet TX Rate",
   "type": "timeseries",
   "description": "TX Rate of VM's  Ethernet Interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_transmit_bytes_total{device='eth0', instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ethernet RX Rate",
   "type": "timeseries",
   "description": "RX Rate of VM's  Ethernet Interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{device='eth0', instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Disk I/O Operations",
   "type": "timeseries",
   "description": "Disk I/O Operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Disk Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "description": "I/O Utilization ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"${instance}\",job=\"node\",device=~\"$diskdevices\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Space",
   "type": "timeseries",
   "description": "Filesystem size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"${instance}\",job=\"node\",device!~\"rootfs\"} - node_filesystem_avail_bytes{instance=\"${instance}\",job=\"node\",device!~\"rootfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "NFS Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "NFS I/O Operations",
   "type": "timeseries",
   "description": "NFS I/O Operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\", operation=~\"READ|WRITE|COMMIT|LOOKUP|CREATE|REMOVE|RENAME|GETATTR|SETATTR|FSSTAT|ACCESS|READDIR\"}[$__rate_interval])",
     "legendFormat": "{{export}} - {{operation}}"
    }
   ]
  },
  {
   "title": "NFS Throughput",
   "type": "timeseries",
   "description": "NFS Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_mountstats_nfs_total_read_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{export}} - Read bytes"
    },
    {
     "expr": "irate(node_mountstats_nfs_total_write_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{export}} - Written bytes"
    }
   ]
  },
  {
   "title": "NFS TX Rate by Instance",
   "type": "timeseries",
   "description": "Cluster heatmap view showing TX throughput for the top 20 busiest VMs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(20, sum by (instance) (\r\n  irate(node_mountstats_nfs_total_write_bytes_total[$__rate_interval])\r\n))\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NFS RX Rate by Instance",
   "type": "timeseries",
   "description": "Cluster heatmap view showing RX throughput for the top 20 busiest VMs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(20, sum by (instance) (\r\n  irate(node_mountstats_nfs_total_read_bytes_total[$__rate_interval])\r\n))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}