{
 "title": "Network View",
 "description": "Network Counters",
 "tags": [ "Moneo Refined" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(node_infiniband_port_packets_received_total{instance=\"$instance\"},port)"
    }
   }
  ]
 },
 "panels": [
  { "title": "InfiniBand", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IB Throughput (RX/TX)",
   "type": "timeseries",
   "description": "The rate of data received/transmitted on the IB port",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_infiniband_port_data_received_bytes_total{instance=~\"$instance\", device!=\"mlx5_an0\"}[$__rate_interval])",
     "legendFormat": "{{device}} - receive"
    },
    {
     "expr": "rate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$instance\", device!=\"mlx5_an0\"}[$__rate_interval])",
     "legendFormat": "{{device}} - transmit"
    }
   ]
  },
  { "title": "Port Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "IB Link Status",
   "type": "state-timeline",
   "description": "Indication of IB Link status. Up:1 and Down:0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_infiniband_physical_state_id{instance=~\"$instance\", device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IB Link Flap Status",
   "type": "state-timeline",
   "description": "Indication of IB Link Flap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "node_infiniband_link_downed_total{instance=\"$instance\",device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Xmit Discards",
   "type": "timeseries",
   "description": "Total number of outbound packets discarded by the port because the port is down or congested.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_infiniband_port_discards_transmitted_total{instance=~\"$instance\", device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Rcv Errors",
   "type": "timeseries",
   "description": "Total number of packets containing an error that were received on the port.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_infiniband_port_errors_received_total{instance=~\"$instance\", device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Rcv Constraint Errors",
   "type": "timeseries",
   "description": "Total number of packets received on the switch physical port that are discarded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_infiniband_port_constraint_errors_received_total{instance=~\"$instance\", device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Xmit Constraint Errors",
   "type": "timeseries",
   "description": "Total number of packets not transmitted from the switch physical port.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_infiniband_port_constraint_errors_transmitted_total{instance=~\"$instance\", device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}