{
 "title": "Combined Node, IB & GPU Metrics Dashboard",
 "description": "Combined Node, IB & GPU Metrics Dashboard",
 "tags": [
  "HPC/AI Researcher",
  "HPC/AI Data scientist"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "instance", "label": "Hostname", "query": { "query": "node_uname_info" } },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=\"$instance\"}, cpu)"
    }
   },
   {
    "name": "diskdevices",
    "label": "Disk Devices",
    "query": {
     "query": "label_values(node_disk_reads_completed_total{instance=\"$instance\"}, device)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(dcgm_fi_dev_gpu_util{instance=\"$instance\"}, gpu)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "description": "Node Spec",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "gauge",
   "description": "Average CPU Utilization",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Utilization",
   "type": "gauge",
   "description": "Average Memory Utilization",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - (avg(node_memory_MemAvailable_bytes{instance=~\"$instance\"}) / avg(node_memory_MemTotal_bytes{instance=~\"$instance\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Clock",
   "type": "timeseries",
   "description": "CPU Clock Speed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=~\"$instance\", cpu=~\"$cpu\"} / 1000000",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time Node has been up",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\"} - node_boot_time_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "CPU Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - avg by (hostname, cpu) (rate(node_cpu_seconds_total{mode='idle', instance=~\"$instance\", cpu=~\"$cpu\"}[5m]))))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Memory Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - node_memory_memavailable_bytes{instance=~\"$instance\"} / node_memory_memtotal_bytes{instance=~\"$instance\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ethernet TX Rate",
   "type": "timeseries",
   "description": "TX Rate of VM's Ethernet Interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_transmit_bytes_total{device='eth0', instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ethernet RX Rate",
   "type": "timeseries",
   "description": "RX Rate of VM's Ethernet Interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{device='eth0', instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "description": "Available memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "node_memory_memavailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Disk Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Disk I/O Operations",
   "type": "timeseries",
   "description": "Disk I/O Operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "Filesystem Space",
   "type": "timeseries",
   "description": "Filesystem size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"${instance}\",job=\"node\",device!~\"rootfs\"} - node_filesystem_avail_bytes{instance=\"${instance}\",job=\"node\",device!~\"rootfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "description": "I/O Utilization ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"${instance}\",job=\"node\",device=~\"$diskdevices\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Space",
   "type": "timeseries",
   "description": "Filesystem size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"${instance}\",job=\"node\",device!~\"rootfs\"} - node_filesystem_avail_bytes{instance=\"${instance}\",job=\"node\",device!~\"rootfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "NFS I/O Operations",
   "type": "timeseries",
   "description": "NFS I/O Operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\", operation=~\"READ|WRITE|COMMIT|LOOKUP|CREATE|REMOVE|RENAME|GETATTR|SETATTR|FSSTAT|ACCESS|READDIR\"}[$__rate_interval])",
     "legendFormat": "{{export}} - {{operation}}"
    }
   ]
  },
  {
   "title": "NFS Throughput",
   "type": "timeseries",
   "description": "NFS Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_mountstats_nfs_total_read_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{export}} - Read bytes"
    },
    {
     "expr": "irate(node_mountstats_nfs_total_write_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{export}} - Written bytes"
    }
   ]
  },
  { "title": "Infiniband Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "IB Link Status",
   "type": "state-timeline",
   "description": "Indication of IB Link status. Up:1 and Down:0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_infiniband_physical_state_id{instance=~\"$instance\", device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IB Link Flap Status",
   "type": "state-timeline",
   "description": "Indication of IB Link Flap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "node_infiniband_link_downed_total{instance=\"$instance\",device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IB TX Rate",
   "type": "timeseries",
   "description": "The rate of data transmitted over InfiniBand.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$instance\", device!=\"mlx5_an0\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IB RX Rate",
   "type": "timeseries",
   "description": "The rate of data received over InfiniBand.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_infiniband_port_data_received_bytes_total{instance=~\"$instance\", device!=\"mlx5_an0\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Xmit Discards",
   "type": "timeseries",
   "description": "Total number of outbound packets discarded by the port because the port is down or congested.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_infiniband_port_discards_transmitted_total{instance=~\"$instance\", device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Xmit Constraint Errors",
   "type": "timeseries",
   "description": "Total number of packets not transmitted from the switch physical port.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_infiniband_port_constraint_errors_transmitted_total{instance=~\"$instance\", device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Rcv Errors",
   "type": "timeseries",
   "description": "Total number of packets containing an error that were received on the port.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_infiniband_port_errors_received_total{instance=~\"$instance\", device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Rcv Constraint Errors",
   "type": "timeseries",
   "description": "Total number of packets received on the switch physical port that are discarded.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_infiniband_port_constraint_errors_received_total{instance=~\"$instance\", device!=\"mlx5_an0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "GPU Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "type": "table",
   "description": "Node Spec",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "dcgm_fi_dev_app_mem_clock{instance=\"$instance\", gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average GPU Utilization",
   "type": "gauge",
   "description": "Average GPU Utilization ",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(dcgm_fi_dev_gpu_util{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average GPU Temperature",
   "type": "gauge",
   "description": "Average GPU Temperature",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dcgm_fi_dev_gpu_temp{instance=~\"$instance\"})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Average Power Usage",
   "type": "gauge",
   "description": "Average Power Usage",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(dcgm_fi_dev_power_usage{instance=~\"$instance\"})",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Copy Utilization",
   "type": "timeseries",
   "description": "Memory utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_mem_copy_util{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU XID Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (gpu) (dcgm_fi_dev_xid_errors{instance=\"$instance\"})",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "GPU utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_util{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "timeseries",
   "description": "Memory clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_mem_clock{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "SM Clock",
   "type": "timeseries",
   "description": "SM clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_sm_clock{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "description": "Memory temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_memory_temp{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "GPU temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_temp{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption",
   "type": "timeseries",
   "description": "Total energy consumption since boot (in mJ)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_total_energy_consumption{instance=~\"$instance\", gpu=~\"$gpu\"} / 10^3",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "description": "Power usage (in W)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_power_usage{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Throttle Code",
   "type": "timeseries",
   "description": "Current throttle code ",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_clock_throttle_reasons{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "XID Codes",
   "type": "table",
   "description": "XID Codes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "dcgm_fi_dev_xid_errors{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "XID"
    }
   ]
  },
  {
   "title": "Power Violation Elapsed Time",
   "type": "timeseries",
   "description": "Power Violation Elapsed Time",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_power_violation{instance=~\"$instance\", gpu=~\"$gpu\"} / 10^6",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "SBE Volatile ECC Errors",
   "type": "timeseries",
   "description": "Total number of single-bit volatile ECC errors",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_fi_dev_ecc_sbe_vol_total{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DBE Volatile ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit volatile ECC errors",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_fi_dev_ecc_dbe_vol_total{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Thermal Violation Elapsed Time",
   "type": "timeseries",
   "description": "Thermal Violation Elapsed Time",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_thermal_violation{instance=~\"$instance\", gpu=~\"$gpu\"} / 10^6",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_fi_dev_ecc_dbe_agg_total{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "SBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of single-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_fi_dev_ecc_sbe_agg_total{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "GPU Profiling Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "SM Active",
   "type": "timeseries",
   "description": "The fraction of time at least one warp was active on a multiprocessor, averaged over all multiprocessors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dcgm_fi_prof_sm_active{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "SM Occupancy",
   "type": "timeseries",
   "description": "The fraction of resident warps on a multiprocessor, relative to the maximum number of concurrent warps supported on a multiprocessor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dcgm_fi_prof_sm_occupancy{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Tensor Active",
   "type": "timeseries",
   "description": "The fraction of cycles the tensor (HMMA / IMMA) pipe was active",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dcgm_fi_prof_pipe_tensor_active{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "FP64 Active",
   "type": "timeseries",
   "description": "The fraction of cycles the FP64 (double precision) pipe was active",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dcgm_fi_prof_pipe_fp64_active{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "FP32 Active",
   "type": "timeseries",
   "description": "The fraction of cycles the FMA (FP32 (single precision), and integer) pipe was active",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dcgm_fi_prof_pipe_fp32_active{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "FP16 Active",
   "type": "timeseries",
   "description": "The fraction of cycles the FP16 (half precision) pipe was active",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dcgm_fi_prof_pipe_fp16_active{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "NVLink TX Rate",
   "type": "timeseries",
   "description": "The rate of data transmitted over NVLink, not including protocol headers, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dcgm_fi_prof_nvlink_tx_bytes{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "NVLink RX Rate",
   "type": "timeseries",
   "description": "The rate of data received over NVLink, not including protocol headers, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dcgm_fi_prof_nvlink_rx_bytes{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "PCIe TX Rate",
   "type": "timeseries",
   "description": "The rate of data transmitted over the PCIe bus, including both protocol headers and data payloads, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dcgm_fi_prof_pcie_tx_bytes{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "PCIe RX Rate",
   "type": "timeseries",
   "description": "The rate of data received over the PCIe bus, including both protocol headers and data payloads, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dcgm_fi_prof_pcie_rx_bytes{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}